name: Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install
        run: yarn

      - name: Prettier
        run: yarn test:lint

      - name: ESLint
        run: yarn test:eslint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install
        run: yarn

      - name: TypeScript
        run: yarn test:types

  versions:
    name: Checking version changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn version check
        run: yarn version check
