name: Release Package
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  release:
    name: Release changed packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install
        run: yarn

      - name: Publish changed packages and create release
        uses: actions/github-script@v7
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          PRERELEASE: ${{ inputs.prerelease }}
        with:
          script: |
            const script = require('./scripts/release-from-ci.js')
            await script({ github, context, exec });
