name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: '${{matrix.platform}} w/ Node.js ${{matrix.node}}.x'
    runs-on: ${{matrix.platform}}

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 24
          - 25
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Yarn install
        run: yarn

      - name: Run tests
        run: yarn test:vitest
