name: E2E Tests
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  tests:
    name: '${{matrix.platform}} w/ Node.js ${{matrix.node}}.x w/ ${{matrix.manager}}'
    runs-on: ${{matrix.platform}}

    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18
          - 19
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        manager:
          - yarn dlx
          - npx

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack
        run: corepack enable && yarn set version berry

      - name: Run E2E - Petstore 3 - with ${{matrix.manager}}
        run: ${{matrix.manager}} @typoas/cli generate -i https://petstore3.swagger.io/api/v3/openapi.json -o test.ts

      - name: Run E2E - Stripe - with ${{matrix.manager}}
        run: ${{matrix.manager}} @typoas/cli generate -i https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json -o test.ts
#      - name: Run E2E - Github - with ${{matrix.manager}}
#        run: ${{matrix.manager}} @typoas/cli generate -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml -o test.ts
