name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: '${{matrix.platform}} w/ Node.js ${{matrix.node}}.x'
    runs-on: ${{matrix.platform}}

    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 14
          - 15
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: yarn test:jest
